# Generated by Django 5.0.2 on 2024-02-17 22:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sokobeauty', '0005_cancellation_payment_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_replies',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comment_replies',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='comment_replies',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to='Sokobeauty.comment'),
        ),
        migrations.AddField(
            model_name='comment_replies',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_replies', to='Sokobeauty.comment_replies'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='comment_replies_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Sokobeauty.comment_replies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'reply')},
            },
        ),
        migrations.DeleteModel(
            name='comment_like',
        ),
    ]
