# Generated by Django 5.0.2 on 2024-02-17 02:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sokobeauty', '0004_vendorprofile'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_methods',
            field=models.ManyToManyField(related_name='users', through='shop.UserPaymentMethod', to='shop.paymentmethod'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hairdresserprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpeg', null=True, upload_to='hairdresser_profiles/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpeg', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='shop_logo',
            field=models.ImageField(blank=True, default='logos/default.jpeg', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
