# Generated by Django 5.0.2 on 2024-02-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sokobeauty', '0005_user_payment_methods_vendorprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
