# Generated by Django 5.0.2 on 2024-02-19 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sokobeauty', '0007_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_replies',
            name='parent_reply',
        ),
        migrations.AlterField(
            model_name='comment_replies',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Sokobeauty.comment'),
        ),
        migrations.CreateModel(
            name='nested_replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_replies', to='Sokobeauty.nested_replies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_nested_replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
