# Generated by Django 5.0.2 on 2024-02-20 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sokobeauty', '0008_remove_comment_replies_parent_reply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment_replies',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_replies', to='Sokobeauty.comment_replies'),
        ),
        migrations.AlterField(
            model_name='comment_replies',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to='Sokobeauty.comment'),
        ),
        migrations.DeleteModel(
            name='nested_replies',
        ),
    ]
