# Generated by Django 5.0.2 on 2024-02-20 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sokobeauty', '0010_remove_comment_replies_parent_reply_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_replies',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Sokobeauty.comment'),
        ),
    ]
