# Generated by Django 5.0.2 on 2024-02-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sokobeauty', '0011_alter_comment_replies_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='nested_replies',
            name='comment_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_replies', to='Sokobeauty.comment_replies'),
        ),
    ]
