# Generated by Django 5.0.2 on 2024-02-20 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sokobeauty', '0013_category_paymentmethod_cart_order_product_orderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='nested_replies_likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nested_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Sokobeauty.nested_replies_likes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nested_reply_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'nested_reply')},
            },
        ),
    ]
