# Generated by Django 5.0.2 on 2024-02-20 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sokobeauty', '0014_nested_replies_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nested_replies_likes',
            name='nested_reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Sokobeauty.nested_replies'),
        ),
    ]
